% Nematic Order Batch Processing Script
% This script scans the folder for all PNG images, runs the nematic analysis 
% on each image, calculates orientation statistics (mean, variance),
% saves overlay figures, angle maps, and individual fluctuation histograms,
% and generates a comparative summary table and overlay plot.

clearvars;
close all;
clc;

% =========================================================================
% USER CONFIGURATIONS
% =========================================================================
% Locate base directory (valeria folder)
baseDir = fileparts(mfilename('fullpath'));
if isempty(baseDir)
    baseDir = pwd;
end
inDir = fullfile(baseDir, 'images');

% Set parameters
sigma = 3;           % Smoothing scale for Gaussian blur
box_size = 64;       % Box size for spatial averaging
Fancy = 0;           % Visualization style (0 = simple, 1 = fancy quiver)

% Output directory for batch results
outDir = fullfile(baseDir, 'batch_results');
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

% Locate all PNG files in directory (case-insensitive search)
filesPng = dir(fullfile(inDir, '*.png'));
filesPNG = dir(fullfile(inDir, '*.PNG'));
files = [filesPng; filesPNG];

% Remove duplicate file listings (if any)
[~, uniqueIdx] = unique({files.name});
files = files(uniqueIdx);

numFiles = numel(files);
if numFiles == 0
    error('No PNG images found in directory: %s', inDir);
end

fprintf('--- Starting Nematic Batch Processing ---\n');
fprintf('Found %d images in folder: %s\n\n', numFiles, inDir);

% Initialize structures to store results for comparison
results = struct();
all_dThetas = cell(numFiles, 1);
names = cell(numFiles, 1);

% Loop through each image
for k = 1:numFiles
    % Build path and file names
    fname = fullfile(inDir, files(k).name);
    [~, baseName, ~] = fileparts(files(k).name);
    names{k} = baseName;
    
    fprintf('[%d/%d] Processing image: %s\n', k, numFiles, files(k).name);
    
    % Close any pre-existing figures to avoid conflicts
    close all;
    
    % 1. Run the core nematic order analysis
    [S_field, theta_field, avg_S, global_S, U, V] = analyze_nematic_order(fname, sigma, box_size, Fancy);
    
    % 2. Calculate angular fluctuations (Delta theta) in degrees
    % Note: theta_field output is already scaled as theta/pi. 
    % Multiplying by 180 directly converts it to degrees.
    dTheta = (theta_field - mean(theta_field(:), 'all')) * 180;
    all_dThetas{k} = dTheta(:);
    
    % Calculate statistical variance (measure of disorder)
    ang_variance = var(dTheta(:));
    
    % Store numerical results
    results(k).name = files(k).name;
    results(k).avg_S = avg_S;
    results(k).global_S = global_S;
    results(k).ang_variance = ang_variance;
    
    % 3. Save figures generated by the analysis function
    % 3. Save figures generated by the analysis function
    figs = findobj('Type', 'figure');
    figs = figs(isgraphics(figs)); % Filter out invalid or deleted graphics handles
    [~, sortIdx] = sort([figs.Number]);
    figs = figs(sortIdx);
    
    % Save Nematic Angle Map (Figure 1)
    if numel(figs) >= 1 && isgraphics(figs(1))
        angleMapPath = fullfile(outDir, sprintf('%s_angle_map.png', baseName));
        saveas(figs(1), angleMapPath);
    end
    
    % Save Director Field Overlay (Figure 2)
    if numel(figs) >= 2 && isgraphics(figs(2))
        overlayPath = fullfile(outDir, sprintf('%s_director_overlay.png', baseName));
        saveas(figs(2), overlayPath);
    end
    
    % 4. Generate and save the fluctuation histogram for this image
    figHist = figure('Visible', 'off');
    histogram(dTheta, 'Normalization', 'probability', 'FaceColor', [0.2 0.6 0.8], 'EdgeColor', 'black');
    xlabel('Angular Fluctuation \Delta\theta (degrees)');
    ylabel('Probability');
    title(sprintf('Orientation Fluctuations: %s', files(k).name));
    grid on;
    set(gca, 'FontName', 'Arial', 'FontSize', 12, 'LineWidth', 1.2);
    
    histPath = fullfile(outDir, sprintf('%s_fluctuation_histogram.png', baseName));
    saveas(figHist, histPath);
    close(figHist);
    
    fprintf('  -> Saved figures to: %s\n', outDir);
    fprintf('  -> Avg S: %.4f | Global S: %.4f | Angular Var: %.4f deg^2\n\n', avg_S, global_S, ang_variance);
end

% =========================================================================
% POST-PROCESSING: COMPARATIVE STATISTICS & PLOTS
% =========================================================================

% Close all individual figures
close all;

% 1. Create a comparative probability histogram overlaying all datasets
figCompare = figure;
hold on;
colors = [0 0.4470 0.7410; 0.8500 0.3250 0.0980; 0.9290 0.6940 0.1250; 0.4940 0.1840 0.5560];

for k = 1:numFiles
    colorIdx = mod(k-1, size(colors, 1)) + 1;
    % Define custom bins for comparative overlay
    histogram(all_dThetas{k}, -90:5:90, 'Normalization', 'probability', ...
              'DisplayStyle', 'stairs', 'LineWidth', 2, ...
              'EdgeColor', colors(colorIdx, :), 'DisplayName', files(k).name);
end

xlabel('Relative Orientation \Delta\theta (degrees)');
ylabel('Probability');
title('Comparison of Director Orientation Fluctuations');
legend('show', 'Location', 'northeast', 'Box', 'off');
grid on;
set(gca, 'FontName', 'Arial', 'FontSize', 14, 'LineWidth', 1.5, 'Box', 'off');

% Save comparative plot
comparePath = fullfile(outDir, 'comparative_histograms.png');
saveas(figCompare, comparePath);
fprintf('Saved comparative plot to: %s\n\n', comparePath);

% 2. Print Summary Table to Command Window and save to CSV
fprintf('=========================================================================\n');
fprintf('%-25s | %-12s | %-12s | %-16s\n', 'Image Filename', 'Average S', 'Global S', 'Angular Var (deg^2)');
fprintf('-------------------------------------------------------------------------\n');

% Open file for CSV export
csvPath = fullfile(outDir, 'nematic_summary.csv');
fid = fopen(csvPath, 'w');
fprintf(fid, 'Image Filename,Average S,Global S,Angular Variance (deg2)\n');

for k = 1:numFiles
    fprintf('%-25s | %-12.4f | %-12.4f | %-16.4f\n', ...
            results(k).name, results(k).avg_S, results(k).global_S, results(k).ang_variance);
    fprintf(fid, '%s,%.6f,%.6f,%.6f\n', ...
            results(k).name, results(k).avg_S, results(k).global_S, results(k).ang_variance);
end
fclose(fid);

fprintf('=========================================================================\n');
fprintf('Saved CSV Summary Report to: %s\n', csvPath);
fprintf('--- Batch Processing Completed Successfully ---\n');
