import os
import glob
import numpy as np
import matplotlib
# Use Agg backend for headless batch processing (saves plots to disk without opening GUI windows)
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from analyze_nematic_order import analyze_nematic_order

# =========================================================================
# CONFIGURATION AND SETUP
# =========================================================================
script_dir = os.path.dirname(os.path.abspath(__file__))
in_dir = os.path.abspath(os.path.join(script_dir, "..", "images"))
out_dir = os.path.abspath(os.path.join(script_dir, "..", "batch_results_python"))

if not os.path.exists(out_dir):
    os.makedirs(out_dir)

# Find all PNG files in parent directory
png_files = glob.glob(os.path.join(in_dir, "*.png")) + glob.glob(os.path.join(in_dir, "*.PNG"))
# Keep unique files
png_files = sorted(list(set(png_files)))

num_files = len(png_files)
if num_files == 0:
    print(f"No PNG images found in: {in_dir}")
    exit(1)

print("--- Starting Python Nematic Batch Processing ---")
print(f"Found {num_files} images in folder: {in_dir}\n")

# Parameters
sigma = 3.0
box_size = 64
fancy = 0

results = []
all_dThetas = []
image_names = []

# Loop through each image
for k, filepath in enumerate(png_files):
    filename = os.path.basename(filepath)
    base_name, _ = os.path.splitext(filename)
    image_names.append(base_name)
    
    print(f"[{k+1}/{num_files}] Processing image: {filename}")
    
    # 1. Run core nematic order analysis
    # Since we are using the Agg backend, analyze_nematic_order will generate the figures
    # but plt.show() will not open them. We will capture and save the open figures.
    plt.close('all') # Clear previous plots
    
    S_field, theta_field, avg_S, global_S, U, V = analyze_nematic_order(
        filename=filepath, 
        sigma=sigma, 
        box_size=box_size, 
        fancy=fancy
    )
    
    # 2. Save the figures generated by the analyze_nematic_order function
    # Figure 1: Nematic Angle Map (from plt.figure() in analyze_nematic_order)
    # Figure 2: Director overlay subplots (from plt.subplots() in analyze_nematic_order)
    fig_ids = plt.get_fignums()
    
    if len(fig_ids) >= 1:
        fig1 = plt.figure(fig_ids[0])
        fig1.savefig(os.path.join(out_dir, f"{base_name}_angle_map.png"), dpi=150)
        
    if len(fig_ids) >= 2:
        fig2 = plt.figure(fig_ids[1])
        fig2.savefig(os.path.join(out_dir, f"{base_name}_director_overlay.png"), dpi=150)
        
    plt.close('all')
    
    # 3. Calculate orientation angle statistics
    # theta_field output is scaled as theta / pi. Multiply by pi, then convert to degrees.
    theta = theta_field * np.pi
    dTheta = (theta - np.mean(theta)) * 180.0 / np.pi
    dTheta_flat = dTheta.flatten()
    all_dThetas.append(dTheta_flat)
    
    ang_variance = np.var(dTheta_flat)
    
    results.append({
        'name': filename,
        'avg_S': avg_S,
        'global_S': global_S,
        'ang_variance': ang_variance
    })
    
    # 4. Generate and save the fluctuation histogram for this specific image
    plt.figure(figsize=(6, 4))
    plt.hist(dTheta_flat, bins=30, weights=np.ones_like(dTheta_flat)/len(dTheta_flat),
             facecolor='skyblue', edgecolor='black', alpha=0.8)
    plt.xlabel('Angular Fluctuation $\Delta\\theta$ (degrees)')
    plt.ylabel('Probability')
    plt.title(f'Orientation Fluctuations: {filename}')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, f"{base_name}_fluctuation_histogram.png"), dpi=150)
    plt.close()
    
    print(f"  -> Saved figures to: {out_dir}")
    print(f"  -> Avg S: {avg_S:.4f} | Global S: {global_S:.4f} | Angular Var: {ang_variance:.4f} deg^2\n")

# =========================================================================
# POST-PROCESSING: COMPARATIVE STATISTICS & PLOTS
# =========================================================================

# 1. Create a comparative probability histogram overlaying all datasets
plt.figure(figsize=(8, 6))

colors = ['blue', 'red', 'orange', 'purple', 'green']
for k in range(num_files):
    color = colors[k % len(colors)]
    # Define same bins to overlay fairly
    counts, bins = np.histogram(all_dThetas[k], bins=np.linspace(-90, 90, 31))
    # Normalize counts to represent probabilities
    probabilities = counts / len(all_dThetas[k])
    
    # Plot stairs histogram manually to mirror MATLAB's stairs histogram style
    bin_centers = 0.5 * (bins[:-1] + bins[1:])
    # Using step plot for stairs appearance
    plt.step(bins[:-1], probabilities, where='post', color=color, label=results[k]['name'], linewidth=2)

plt.xlabel(r'Relative Orientation $\Delta\theta$ (degrees)', fontsize=12)
plt.ylabel('Probability', fontsize=12)
plt.title('Comparison of Director Orientation Fluctuations', fontsize=14)
plt.ylim(0, 0.12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.legend(frameon=False, fontsize=10)

ax = plt.gca()
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.set_facecolor('none')

compare_path = os.path.join(out_dir, "comparative_histograms.png")
plt.tight_layout()
plt.savefig(compare_path, dpi=200)
plt.close()
print(f"Saved comparative plot to: {compare_path}\n")

# 2. Print Summary Table to Console and save to CSV
print("=========================================================================")
print(f"{'Image Filename':<25} | {'Average S':<12} | {'Global S':<12} | {'Angular Var (deg^2)':<16}")
print("-------------------------------------------------------------------------")

csv_path = os.path.join(out_dir, "nematic_summary.csv")
with open(csv_path, 'w') as f:
    f.write("Image Filename,Average S,Global S,Angular Variance (deg2)\n")
    for r in results:
        print(f"{r['name']:<25} | {r['avg_S']:<12.4f} | {r['global_S']:<12.4f} | {r['ang_variance']:<16.4f}")
        f.write(f"{r['name']},{r['avg_S']:.6f},{r['global_S']:.6f},{r['ang_variance']:.6f}\n")

print("=========================================================================")
print(f"Saved CSV Summary Report to: {csv_path}")
print("--- Batch Processing Completed Successfully ---")
